# .github/workflows/code-quality.yml
name: Format Check

on:
  pull_request:
    branches: [main]
    # paths:
    #   - "**.py"
    #   - "**.ipynb"

jobs:
  black:
    name: Check Black Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install 'black[jupyter]'
          
      - name: Check formatting
        run: |
          black --check -v --config pyproject.toml .
        # This will fail if any files are not properly formatted